---
name: DBIx-Custom-SQL-Template
version: 0.0101
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Custamizable SQL Template for DBIx::Custom
license: perl
resources:
  license: ~
requires:
  Object::Simple: 2.0702
build_requires:
  Test::More: 0
provides:
  DBIx::Custom::SQL::Template:
    file: lib/DBIx/Custom/SQL/Template.pm
    version: 0.0101
  DBIx::Custom::SQL::Template::TagProcessor:
    file: lib/DBIx/Custom/SQL/Template.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
